from pathlib import Path

import pandas as pd
import streamlit as st

from db import get_table_counts, save_review_decision


# ------------------------------------------------------------
# File paths
# ------------------------------------------------------------
# The comparison file is generated by compare_triage.py.
# It contains rules outputs, LLM outputs, hybrid recommendations,
# correctness flags, and human-review recommendations.
COMPARISON_FILE = Path("data/triage_comparison.csv")


# ------------------------------------------------------------
# Review option values
# ------------------------------------------------------------
# These are the valid values a reviewer can choose when approving
# or overriding recommendations.
TRIAGE_CATEGORIES = [
    "Billing",
    "Account Access",
    "Security / Compliance",
    "Product Question",
    "Technical Issue",
    "Other",
]

TRIAGE_URGENCIES = [
    "Critical",
    "High",
    "Medium",
    "Low",
]

RECOMMENDED_OWNERS = [
    "Finance Operations",
    "Service Desk",
    "Security Operations",
    "Customer Success",
    "Application Engineering",
]

REVIEW_STATUSES = [
    "Pending",
    "Approved",
    "Overridden",
    "Needs Follow-Up",
]


# ------------------------------------------------------------
# Sort order helpers
# ------------------------------------------------------------
# Alphabetical sorting is bad for urgency because it would put
# High, Low, Medium, Critical in the wrong operational order.
URGENCY_RANK = {
    "Critical": 1,
    "High": 2,
    "Medium": 3,
    "Low": 4,
}


def load_comparison_data() -> pd.DataFrame:
    """
    Load the comparison dataset created by compare_triage.py.

    This is the core dataset for the app because it contains the rules output,
    LLM output, hybrid recommendation, and human-review flags.
    """

    if not COMPARISON_FILE.exists():
        st.error(
            "Missing data/triage_comparison.csv. Run python compare_triage.py first."
        )
        st.stop()

    return pd.read_csv(COMPARISON_FILE)


def derive_review_reason(row: pd.Series) -> str:
    """
    Create a human-readable reason explaining why an incident needs review.

    This is more useful than a simple True/False review flag because reviewers
    need to know what kind of issue they are looking at.
    """

    reasons = []

    if row["hybrid_triage_urgency"] == "Critical":
        reasons.append("Critical urgency")

    if not row["category_agreement"]:
        reasons.append("Category disagreement")

    if not row["urgency_agreement"]:
        reasons.append("Urgency disagreement")

    if not row["owner_agreement"]:
        reasons.append("Owner disagreement")

    if row["llm_confidence"] < 0.70:
        reasons.append("Low LLM confidence")

    if not reasons:
        return "No review trigger"

    return "; ".join(reasons)


def prepare_review_dataframe(df: pd.DataFrame) -> pd.DataFrame:
    """
    Add user-facing review fields to the comparison dataset.

    The reviewed values default to the hybrid recommendation because Lesson 5
    showed that the hybrid approach is strongest for this dataset.
    """

    review_df = df.copy()

    # Add sort fields and review reasons.
    review_df["urgency_rank"] = review_df["hybrid_triage_urgency"].map(URGENCY_RANK)
    review_df["review_reason"] = review_df.apply(derive_review_reason, axis=1)

    # Initialize final reviewer decision fields from the hybrid recommendation.
    review_df["reviewed_category"] = review_df["hybrid_triage_category"]
    review_df["reviewed_urgency"] = review_df["hybrid_triage_urgency"]
    review_df["reviewed_owner"] = review_df["hybrid_recommended_owner"]

    # Track reviewer workflow state.
    review_df["review_status"] = "Pending"
    review_df["review_notes"] = ""

    return review_df


def initialize_session_state() -> None:
    """
    Initialize Streamlit session state.

    Streamlit reruns the script after interactions. Session state lets us keep
    review decisions during the user's active browser session.
    """

    if "review_df" not in st.session_state:
        raw_df = load_comparison_data()
        st.session_state.review_df = prepare_review_dataframe(raw_df)

    if "selected_incident_number" not in st.session_state:
        review_candidates = st.session_state.review_df[
            st.session_state.review_df["recommended_for_human_review"] == True
        ]

        if not review_candidates.empty:
            st.session_state.selected_incident_number = review_candidates.iloc[0]["number"]
        else:
            st.session_state.selected_incident_number = st.session_state.review_df.iloc[0]["number"]


def get_review_candidates(df: pd.DataFrame) -> pd.DataFrame:
    """
    Return only incidents recommended for human review.

    This is the default work queue because the primary user task is to process
    exceptions, not browse every incident.
    """

    candidates = df[df["recommended_for_human_review"] == True].copy()

    # Sort by operational priority by default.
    candidates = candidates.sort_values(
        by=["urgency_rank", "llm_confidence", "number"],
        ascending=[True, True, True],
    )

    return candidates


def apply_queue_filters(df: pd.DataFrame) -> pd.DataFrame:
    """
    Apply queue filters and sorting controls.

    These controls let a reviewer quickly focus on the highest-priority
    incidents or a specific type of disagreement.
    """

    st.sidebar.header("Queue Controls")

    sort_by = st.sidebar.selectbox(
        "Sort review queue by",
        options=[
            "Urgency",
            "Category",
            "Owner",
            "Disagreement Type",
            "LLM Confidence",
            "Incident Number",
        ],
    )

    urgency_filter = st.sidebar.multiselect(
        "Urgency",
        options=TRIAGE_URGENCIES,
        default=TRIAGE_URGENCIES,
    )

    category_filter = st.sidebar.multiselect(
        "Category",
        options=TRIAGE_CATEGORIES,
        default=TRIAGE_CATEGORIES,
    )

    owner_filter = st.sidebar.multiselect(
        "Owner",
        options=RECOMMENDED_OWNERS,
        default=RECOMMENDED_OWNERS,
    )

    disagreement_filter = st.sidebar.multiselect(
        "Review reason",
        options=[
            "Critical urgency",
            "Category disagreement",
            "Urgency disagreement",
            "Owner disagreement",
            "Low LLM confidence",
        ],
        default=[],
    )

    min_confidence = st.sidebar.slider(
        "Minimum LLM confidence",
        min_value=0.0,
        max_value=1.0,
        value=0.0,
        step=0.05,
    )

    filtered_df = df[
        df["hybrid_triage_urgency"].isin(urgency_filter)
        & df["hybrid_triage_category"].isin(category_filter)
        & df["hybrid_recommended_owner"].isin(owner_filter)
        & (df["llm_confidence"] >= min_confidence)
    ].copy()

    # If one or more review reasons are selected, keep rows matching any selected reason.
    if disagreement_filter:
        reason_mask = filtered_df["review_reason"].apply(
            lambda value: any(reason in value for reason in disagreement_filter)
        )
        filtered_df = filtered_df[reason_mask].copy()

    # Apply user-selected sorting.
    if sort_by == "Urgency":
        filtered_df = filtered_df.sort_values(
            by=["urgency_rank", "llm_confidence", "number"],
            ascending=[True, True, True],
        )
    elif sort_by == "Category":
        filtered_df = filtered_df.sort_values(by=["hybrid_triage_category", "urgency_rank"])
    elif sort_by == "Owner":
        filtered_df = filtered_df.sort_values(by=["hybrid_recommended_owner", "urgency_rank"])
    elif sort_by == "Disagreement Type":
        filtered_df = filtered_df.sort_values(by=["review_reason", "urgency_rank"])
    elif sort_by == "LLM Confidence":
        filtered_df = filtered_df.sort_values(by=["llm_confidence", "urgency_rank"])
    elif sort_by == "Incident Number":
        filtered_df = filtered_df.sort_values(by=["number"])

    return filtered_df


def render_top_metrics(df: pd.DataFrame) -> None:
    """
    Render operational metrics across the full dataset.

    These metrics give the reviewer quick context before working the queue.
    """

    total_incidents = len(df)
    review_candidates = df["recommended_for_human_review"].sum()
    pending_reviews = (df["review_status"] == "Pending").sum()
    approved_reviews = (df["review_status"] == "Approved").sum()
    overridden_reviews = (df["review_status"] == "Overridden").sum()

    col1, col2, col3, col4, col5 = st.columns(5)

    col1.metric("Total Incidents", int(total_incidents))
    col2.metric("Review Candidates", int(review_candidates))
    col3.metric("Pending", int(pending_reviews))
    col4.metric("Approved", int(approved_reviews))
    col5.metric("Overridden", int(overridden_reviews))

    # Show current database row counts so the user can see persistence working.
    db_counts = get_table_counts()

    st.caption(
        f"Database records — incidents: {db_counts['incidents']}, "
        f"predictions: {db_counts['triage_predictions']}, "
        f"review decisions: {db_counts['review_decisions']}"
    )


def render_queue_table(queue_df: pd.DataFrame) -> None:
    """
    Render the human review queue.

    The user selects an incident here, then makes the decision in the decision
    workspace below.
    """

    st.subheader("Human Review Queue")

    if queue_df.empty:
        st.info("No human review candidates match the current filters.")
        return

    queue_columns = [
        "number",
        "company",
        "short_description",
        "hybrid_triage_urgency",
        "hybrid_triage_category",
        "hybrid_recommended_owner",
        "review_reason",
        "llm_confidence",
        "review_status",
    ]

    st.dataframe(
        queue_df[queue_columns],
        use_container_width=True,
        hide_index=True,
    )

    selected_number = st.selectbox(
        "Select incident to review",
        options=queue_df["number"].tolist(),
        index=0,
    )

    st.session_state.selected_incident_number = selected_number


def get_selected_incident() -> pd.Series:
    """
    Return the currently selected incident from session state.
    """

    df = st.session_state.review_df
    selected_number = st.session_state.selected_incident_number

    selected_rows = df[df["number"] == selected_number]

    if selected_rows.empty:
        return df.iloc[0]

    return selected_rows.iloc[0]


def update_selected_incident(
    reviewed_category: str,
    reviewed_urgency: str,
    reviewed_owner: str,
    review_status: str,
    review_notes: str,
    decision_source: str,
) -> None:
    """
    Update the selected incident in the session-state dataframe and save the
    decision to SQLite.

    This makes decision buttons and manual overrides durable beyond the current
    Streamlit browser session.
    """

    selected_number = st.session_state.selected_incident_number
    selected_mask = st.session_state.review_df["number"] == selected_number

    # Update Streamlit session state so the UI reflects the decision immediately.
    st.session_state.review_df.loc[selected_mask, "reviewed_category"] = reviewed_category
    st.session_state.review_df.loc[selected_mask, "reviewed_urgency"] = reviewed_urgency
    st.session_state.review_df.loc[selected_mask, "reviewed_owner"] = reviewed_owner
    st.session_state.review_df.loc[selected_mask, "review_status"] = review_status
    st.session_state.review_df.loc[selected_mask, "review_notes"] = review_notes

    # Save the review decision to SQLite so it is preserved after app restart.
    save_review_decision(
        incident_number=selected_number,
        reviewed_category=reviewed_category,
        reviewed_urgency=reviewed_urgency,
        reviewed_owner=reviewed_owner,
        review_status=review_status,
        review_notes=review_notes,
        decision_source=decision_source,
    )


def render_recommendation_comparison(selected: pd.Series) -> None:
    """
    Render source, rules, LLM, and hybrid recommendations side by side.

    This is the evidence panel for the review decision.
    """

    source_col, rules_col, llm_col, hybrid_col = st.columns(4)

    with source_col:
        st.markdown("#### Source Incident")
        st.write(f"**Number:** {selected['number']}")
        st.write(f"**Company:** {selected['company']}")
        st.write(f"**Short Description:** {selected['short_description']}")
        st.write(f"**Impact:** {selected['source_impact']}")
        st.write(f"**Urgency:** {selected['source_urgency']}")
        st.write(f"**Priority:** {selected['source_priority']}")

    with rules_col:
        st.markdown("#### Rules")
        st.write(f"**Category:** {selected['rules_triage_category']}")
        st.write(f"**Urgency:** {selected['rules_triage_urgency']}")
        st.write(f"**Owner:** {selected['rules_recommended_owner']}")
        st.write(f"**Confidence:** {selected['rules_confidence']}")

    with llm_col:
        st.markdown("#### LLM")
        st.write(f"**Category:** {selected['llm_triage_category']}")
        st.write(f"**Urgency:** {selected['llm_triage_urgency']}")
        st.write(f"**Owner:** {selected['llm_recommended_owner']}")
        st.write(f"**Confidence:** {selected['llm_confidence']}")
        st.write(f"**Summary:** {selected['llm_summary']}")

    with hybrid_col:
        st.markdown("#### Hybrid Recommendation")
        st.write(f"**Category:** {selected['hybrid_triage_category']}")
        st.write(f"**Urgency:** {selected['hybrid_triage_urgency']}")
        st.write(f"**Owner:** {selected['hybrid_recommended_owner']}")
        st.write(f"**Review Reason:** {selected['review_reason']}")


def render_decision_workspace() -> None:
    """
    Render the main decision workspace for the selected incident.

    The reviewer can approve the hybrid recommendation, choose the rules result,
    choose the LLM result, or manually override fields.
    """

    selected = get_selected_incident()

    st.subheader("Decision Workspace")

    render_recommendation_comparison(selected)

    st.markdown("#### Full Description")
    st.write(selected["description"])

    st.markdown("#### LLM Reasoning and Next Action")
    st.write(f"**Reasoning Summary:** {selected['llm_reasoning_summary']}")
    st.write(f"**Next Action:** {selected['llm_next_action']}")

    st.markdown("#### Make Decision")

    button_col1, button_col2, button_col3, button_col4 = st.columns(4)

    # Approve the hybrid recommendation.
    if button_col1.button("Approve Hybrid", use_container_width=True):
        update_selected_incident(
            reviewed_category=selected["hybrid_triage_category"],
            reviewed_urgency=selected["hybrid_triage_urgency"],
            reviewed_owner=selected["hybrid_recommended_owner"],
            review_status="Approved",
            review_notes="Approved hybrid recommendation.",
            decision_source="hybrid",
        )
        st.success("Approved hybrid recommendation.")

    # Use the pure rules recommendation.
    if button_col2.button("Use Rules", use_container_width=True):
        update_selected_incident(
            reviewed_category=selected["rules_triage_category"],
            reviewed_urgency=selected["rules_triage_urgency"],
            reviewed_owner=selected["rules_recommended_owner"],
            review_status="Overridden",
            review_notes="Used rules-based recommendation.",
            decision_source="rules",
        )
        st.success("Applied rules-based recommendation.")

    # Use the pure LLM recommendation.
    if button_col3.button("Use LLM", use_container_width=True):
        update_selected_incident(
            reviewed_category=selected["llm_triage_category"],
            reviewed_urgency=selected["llm_triage_urgency"],
            reviewed_owner=selected["llm_recommended_owner"],
            review_status="Overridden",
            review_notes="Used LLM recommendation.",
            decision_source="llm",
        )
        st.success("Applied LLM recommendation.")

    # Mark the incident for follow-up without changing the reviewed values.
    if button_col4.button("Needs Follow-Up", use_container_width=True):
        update_selected_incident(
            reviewed_category=selected["reviewed_category"],
            reviewed_urgency=selected["reviewed_urgency"],
            reviewed_owner=selected["reviewed_owner"],
            review_status="Needs Follow-Up",
            review_notes="Reviewer marked this incident for follow-up.",
            decision_source="follow_up",
        )
        st.warning("Marked for follow-up.")

    st.markdown("#### Manual Override")

    manual_col1, manual_col2, manual_col3 = st.columns(3)

    reviewed_category = manual_col1.selectbox(
        "Reviewed category",
        options=TRIAGE_CATEGORIES,
        index=TRIAGE_CATEGORIES.index(selected["reviewed_category"]),
    )

    reviewed_urgency = manual_col2.selectbox(
        "Reviewed urgency",
        options=TRIAGE_URGENCIES,
        index=TRIAGE_URGENCIES.index(selected["reviewed_urgency"]),
    )

    reviewed_owner = manual_col3.selectbox(
        "Reviewed owner",
        options=RECOMMENDED_OWNERS,
        index=RECOMMENDED_OWNERS.index(selected["reviewed_owner"]),
    )

    review_notes = st.text_area(
        "Review notes",
        value=selected["review_notes"] if pd.notna(selected["review_notes"]) else "",
    )

    if st.button("Save Manual Override", use_container_width=True):
        update_selected_incident(
            reviewed_category=reviewed_category,
            reviewed_urgency=reviewed_urgency,
            reviewed_owner=reviewed_owner,
            review_status="Overridden",
            review_notes=review_notes,
            decision_source="manual_override",
        )
        st.success("Manual override saved.")


def render_all_incidents_tab() -> None:
    """
    Render a searchable all-incidents view.

    This is for users who need to inspect or modify incidents that were not
    automatically included in the human review queue.
    """

    st.subheader("All Incidents")

    df = st.session_state.review_df.copy()

    search_text = st.text_input("Search short description or company")

    if search_text:
        search_lower = search_text.lower()
        df = df[
            df["short_description"].str.lower().str.contains(search_lower)
            | df["company"].str.lower().str.contains(search_lower)
        ]

    columns = [
        "number",
        "company",
        "short_description",
        "hybrid_triage_urgency",
        "hybrid_triage_category",
        "hybrid_recommended_owner",
        "recommended_for_human_review",
        "review_status",
        "review_reason",
    ]

    st.dataframe(df[columns], use_container_width=True, hide_index=True)


def render_analytics_tab() -> None:
    """
    Render analytics for the full incident set.

    This supports users who want system-level performance stats, not just
    ticket-by-ticket review.
    """

    st.subheader("Analytics")

    df = st.session_state.review_df

    st.markdown("### Review Reason Counts")
    review_reason_counts = df["review_reason"].value_counts().reset_index()
    review_reason_counts.columns = ["Review Reason", "Count"]
    st.dataframe(review_reason_counts, use_container_width=True, hide_index=True)

    st.markdown("### Hybrid Urgency Distribution")
    urgency_counts = (
        df["hybrid_triage_urgency"]
        .value_counts()
        .reindex(TRIAGE_URGENCIES)
        .fillna(0)
        .astype(int)
        .reset_index()
    )
    urgency_counts.columns = ["Urgency", "Count"]
    st.bar_chart(urgency_counts.set_index("Urgency"))

    st.markdown("### Hybrid Owner Workload")
    owner_counts = df["hybrid_recommended_owner"].value_counts().reset_index()
    owner_counts.columns = ["Owner", "Count"]
    st.dataframe(owner_counts, use_container_width=True, hide_index=True)

    st.markdown("### Comparison Outcomes")
    outcome_cols = st.columns(3)

    with outcome_cols[0]:
        st.write("Category")
        st.dataframe(
            df["category_comparison_outcome"].value_counts().reset_index(),
            use_container_width=True,
            hide_index=True,
        )

    with outcome_cols[1]:
        st.write("Urgency")
        st.dataframe(
            df["urgency_comparison_outcome"].value_counts().reset_index(),
            use_container_width=True,
            hide_index=True,
        )

    with outcome_cols[2]:
        st.write("Owner")
        st.dataframe(
            df["owner_comparison_outcome"].value_counts().reset_index(),
            use_container_width=True,
            hide_index=True,
        )


def render_export_tab() -> None:
    """
    Render export controls for reviewed data.

    This lets the user download the current review state for downstream analysis
    or operational handoff.
    """

    st.subheader("Export")

    full_df = st.session_state.review_df.copy()

    review_candidates = full_df[full_df["recommended_for_human_review"] == True]
    overridden = full_df[full_df["review_status"] == "Overridden"]
    approved = full_df[full_df["review_status"] == "Approved"]

    st.download_button(
        label="Download all reviewed incidents",
        data=full_df.to_csv(index=False),
        file_name="reviewed_incidents_all.csv",
        mime="text/csv",
        use_container_width=True,
    )

    st.download_button(
        label="Download human review candidates",
        data=review_candidates.to_csv(index=False),
        file_name="reviewed_incidents_candidates.csv",
        mime="text/csv",
        use_container_width=True,
    )

    st.download_button(
        label="Download overridden incidents",
        data=overridden.to_csv(index=False),
        file_name="reviewed_incidents_overridden.csv",
        mime="text/csv",
        use_container_width=True,
    )

    st.download_button(
        label="Download approved incidents",
        data=approved.to_csv(index=False),
        file_name="reviewed_incidents_approved.csv",
        mime="text/csv",
        use_container_width=True,
    )


def main() -> None:
    """
    Main Streamlit app entry point.

    This app is organized around the user's actual workflow:
    review exception candidates, inspect recommendations, make a decision,
    optionally inspect all incidents, view analytics, and export results.
    """

    st.set_page_config(
        page_title="Triage Workbench",
        layout="wide",
    )

    initialize_session_state()

    st.title("Triage Workbench")
    st.caption(
        "Human review queue for hybrid rules + LLM incident triage recommendations."
    )

    render_top_metrics(st.session_state.review_df)

    review_tab, all_incidents_tab, analytics_tab, export_tab = st.tabs(
        [
            "Review Queue",
            "All Incidents",
            "Analytics",
            "Export",
        ]
    )

    with review_tab:
        review_candidates = get_review_candidates(st.session_state.review_df)
        filtered_queue = apply_queue_filters(review_candidates)

        render_queue_table(filtered_queue)
        render_decision_workspace()

    with all_incidents_tab:
        render_all_incidents_tab()

    with analytics_tab:
        render_analytics_tab()

    with export_tab:
        render_export_tab()


if __name__ == "__main__":
    main()