from pathlib import Path

import pandas as pd
import streamlit as st


# ------------------------------------------------------------
# File paths
# ------------------------------------------------------------
# These constants define where the app reads and writes data.
# The LLM output file is generated by llm_triage.py.
LLM_RESULTS_FILE = Path("data/llm_triaged_incidents.csv")
REVIEWED_OUTPUT_FILE = Path("data/reviewed_incidents.csv")


# ------------------------------------------------------------
# Allowed override values
# ------------------------------------------------------------
# These lists define the valid values a human reviewer can choose.
# Keeping them centralized makes the UI easier to maintain.
TRIAGE_CATEGORIES = [
    "Billing",
    "Account Access",
    "Security / Compliance",
    "Product Question",
    "Technical Issue",
    "Other",
]

TRIAGE_URGENCIES = [
    "Low",
    "Medium",
    "High",
    "Critical",
]

RECOMMENDED_OWNERS = [
    "Finance Operations",
    "Service Desk",
    "Security Operations",
    "Customer Success",
    "Application Engineering",
]


def load_llm_results() -> pd.DataFrame:
    """
    Load LLM triage results from CSV.

    This function keeps data loading separate from UI rendering.
    That makes the app easier to test and extend later.
    """

    if not LLM_RESULTS_FILE.exists():
        st.error(
            "LLM results file not found. Run `python llm_triage.py --limit 25` first."
        )
        st.stop()

    return pd.read_csv(LLM_RESULTS_FILE)


def prepare_review_dataframe(df: pd.DataFrame) -> pd.DataFrame:
    """
    Add human-review columns to the LLM results.

    The LLM gives recommendations. The reviewer can approve or override them.
    """

    reviewed_df = df.copy()

    # These columns represent the final human-approved triage values.
    reviewed_df["reviewed_category"] = reviewed_df["llm_triage_category"]
    reviewed_df["reviewed_urgency"] = reviewed_df["llm_triage_urgency"]
    reviewed_df["reviewed_owner"] = reviewed_df["llm_recommended_owner"]

    # Review status fields let a user track what has been approved.
    reviewed_df["review_status"] = "Pending"
    reviewed_df["review_notes"] = ""

    return reviewed_df


def apply_filters(df: pd.DataFrame) -> pd.DataFrame:
    """
    Apply sidebar filters to the review queue.

    Filters help reviewers focus on the highest-risk or most relevant records.
    """

    filtered_df = df.copy()

    st.sidebar.header("Filters")

    urgency_filter = st.sidebar.multiselect(
        "LLM urgency",
        options=TRIAGE_URGENCIES,
        default=TRIAGE_URGENCIES,
    )

    category_filter = st.sidebar.multiselect(
        "LLM category",
        options=TRIAGE_CATEGORIES,
        default=TRIAGE_CATEGORIES,
    )

    owner_filter = st.sidebar.multiselect(
        "LLM owner",
        options=RECOMMENDED_OWNERS,
        default=RECOMMENDED_OWNERS,
    )

    min_confidence = st.sidebar.slider(
        "Minimum LLM confidence",
        min_value=0.0,
        max_value=1.0,
        value=0.0,
        step=0.05,
    )

    filtered_df = filtered_df[
        filtered_df["llm_triage_urgency"].isin(urgency_filter)
        & filtered_df["llm_triage_category"].isin(category_filter)
        & filtered_df["llm_recommended_owner"].isin(owner_filter)
        & (filtered_df["llm_confidence"] >= min_confidence)
    ]

    return filtered_df


def render_metrics(df: pd.DataFrame) -> None:
    """
    Render high-level metrics for the review queue.

    These metrics make the app useful as an operational dashboard,
    not just a table viewer.
    """

    total_count = len(df)
    critical_count = (df["llm_triage_urgency"] == "Critical").sum()
    high_count = (df["llm_triage_urgency"] == "High").sum()
    low_confidence_count = (df["llm_confidence"] < 0.70).sum()

    col1, col2, col3, col4 = st.columns(4)

    col1.metric("Visible Incidents", total_count)
    col2.metric("Critical", critical_count)
    col3.metric("High", high_count)
    col4.metric("Low Confidence", low_confidence_count)


def render_incident_detail(df: pd.DataFrame) -> None:
    """
    Render a detailed view for one selected incident.

    This gives the reviewer enough context to decide whether the LLM
    recommendation is acceptable.
    """

    st.subheader("Incident Detail")

    if df.empty:
        st.info("No incidents match the current filters.")
        return

    incident_numbers = df["number"].tolist()

    selected_number = st.selectbox(
        "Select incident",
        options=incident_numbers,
    )

    selected = df[df["number"] == selected_number].iloc[0]

    left_col, right_col = st.columns(2)

    with left_col:
        st.markdown("### Source Incident")
        st.write(f"**Number:** {selected['number']}")
        st.write(f"**Company:** {selected['company']}")
        st.write(f"**Short Description:** {selected['short_description']}")
        st.write(f"**Description:** {selected['description']}")
        st.write(f"**Source Category:** {selected['source_category']}")
        st.write(f"**Source Impact:** {selected['source_impact']}")
        st.write(f"**Source Urgency:** {selected['source_urgency']}")
        st.write(f"**Source Priority:** {selected['source_priority']}")

    with right_col:
        st.markdown("### LLM Recommendation")
        st.write(f"**Category:** {selected['llm_triage_category']}")
        st.write(f"**Urgency:** {selected['llm_triage_urgency']}")
        st.write(f"**Owner:** {selected['llm_recommended_owner']}")
        st.write(f"**Confidence:** {selected['llm_confidence']}")
        st.write(f"**Summary:** {selected['llm_summary']}")
        st.write(f"**Next Action:** {selected['llm_next_action']}")
        st.write(f"**Reasoning Summary:** {selected['llm_reasoning_summary']}")


def render_review_editor(df: pd.DataFrame) -> pd.DataFrame:
    """
    Render an editable review table.

    st.data_editor returns the edited dataframe. We use this to capture
    human overrides for category, urgency, owner, status, and notes.
    """

    st.subheader("Review Queue")

    editable_columns = [
        "number",
        "company",
        "short_description",
        "llm_triage_urgency",
        "llm_triage_category",
        "llm_recommended_owner",
        "llm_confidence",
        "reviewed_urgency",
        "reviewed_category",
        "reviewed_owner",
        "review_status",
        "review_notes",
    ]

    edited_df = st.data_editor(
        df[editable_columns],
        hide_index=True,
        use_container_width=True,
        disabled=[
            "number",
            "company",
            "short_description",
            "llm_triage_urgency",
            "llm_triage_category",
            "llm_recommended_owner",
            "llm_confidence",
        ],
        column_config={
            "reviewed_urgency": st.column_config.SelectboxColumn(
                "Reviewed Urgency",
                options=TRIAGE_URGENCIES,
            ),
            "reviewed_category": st.column_config.SelectboxColumn(
                "Reviewed Category",
                options=TRIAGE_CATEGORIES,
            ),
            "reviewed_owner": st.column_config.SelectboxColumn(
                "Reviewed Owner",
                options=RECOMMENDED_OWNERS,
            ),
            "review_status": st.column_config.SelectboxColumn(
                "Review Status",
                options=["Pending", "Approved", "Overridden"],
            ),
        },
    )

    return edited_df


def render_download_button(df: pd.DataFrame) -> None:
    """
    Render a download button for reviewed incidents.

    This lets the reviewer export the approved/overridden results.
    """

    csv_data = df.to_csv(index=False)

    st.download_button(
        label="Download reviewed incidents CSV",
        data=csv_data,
        file_name="reviewed_incidents.csv",
        mime="text/csv",
    )


def main():
    """
    Main Streamlit app entry point.

    The app loads LLM triage results, applies filters, displays incident context,
    captures human review edits, and enables CSV export.
    """

    st.set_page_config(
        page_title="Incident Triage Review",
        layout="wide",
    )

    st.title("Incident Triage Review")
    st.caption(
        "Human-in-the-loop review app for LLM-generated ITSM incident triage."
    )

    # Load LLM results once and initialize review data in session state.
    # Session state prevents the review dataframe from being reset on every UI rerun.
    if "review_df" not in st.session_state:
        raw_df = load_llm_results()
        st.session_state.review_df = prepare_review_dataframe(raw_df)

    # Apply sidebar filters to the current review dataset.
    filtered_df = apply_filters(st.session_state.review_df)

    # Render top-level metrics.
    render_metrics(filtered_df)

    # Render detailed context for one selected incident.
    render_incident_detail(filtered_df)

    # Render editable review queue.
    edited_df = render_review_editor(filtered_df)

    # Store the edited dataframe in session state for export.
    st.session_state.edited_review_df = edited_df

    # Render export button.
    render_download_button(edited_df)


if __name__ == "__main__":
    main()