from pathlib import Path

import pandas as pd

from main import triage_tickets


# ------------------------------------------------------------
# File paths
# ------------------------------------------------------------
# The expected results file contains ground-truth labels.
EXPECTED_RESULTS_FILE = Path("data/expected_results.csv")

# The LLM results file is generated by llm_triage.py.
LLM_RESULTS_FILE = Path("data/llm_triaged_incidents.csv")

# The comparison output file will be generated by this script.
COMPARISON_OUTPUT_FILE = Path("data/triage_comparison.csv")


def calculate_accuracy(df: pd.DataFrame, actual_column: str, expected_column: str) -> float:
    """
    Calculate the percentage of rows where the actual value matches the expected value.
    """

    # Count how many rows match.
    correct_count = (df[actual_column] == df[expected_column]).sum()

    # Count the total rows being evaluated.
    total_count = len(df)

    # Avoid division by zero if the dataframe is empty.
    if total_count == 0:
        return 0.0

    return correct_count / total_count


def load_comparison_inputs() -> pd.DataFrame:
    """
    Load rules-based results, LLM results, and expected labels into one dataframe.

    The rules-based results are generated directly by calling triage_tickets().
    The LLM results are loaded from the CSV generated by llm_triage.py.
    """

    # Generate rules-based triage results from the current incident dataset.
    rules_results = triage_tickets()

    # Load LLM-generated triage results.
    if not LLM_RESULTS_FILE.exists():
        raise FileNotFoundError(
            f"{LLM_RESULTS_FILE} not found. Run llm_triage.py first."
        )

    llm_results = pd.read_csv(LLM_RESULTS_FILE)

    # Load expected labels.
    expected_results = pd.read_csv(EXPECTED_RESULTS_FILE)

    # Select and rename rules columns so they are clearly identified.
    rules_subset = rules_results[
        [
            "number",
            "company",
            "short_description",
            "description",
            "source_impact",
            "source_urgency",
            "source_priority",
            "triage_category",
            "triage_urgency",
            "recommended_owner",
            "confidence",
            "requires_human_review",
        ]
    ].rename(
        columns={
            "triage_category": "rules_triage_category",
            "triage_urgency": "rules_triage_urgency",
            "recommended_owner": "rules_recommended_owner",
            "confidence": "rules_confidence",
            "requires_human_review": "rules_requires_human_review",
        }
    )

    # Select and rename LLM columns so they are clearly identified.
    llm_subset = llm_results[
        [
            "number",
            "llm_triage_category",
            "llm_triage_urgency",
            "llm_recommended_owner",
            "llm_confidence",
            "llm_summary",
            "llm_next_action",
            "llm_reasoning_summary",
        ]
    ]

    # Merge rules, LLM, and expected labels on incident number.
    comparison = (
        rules_subset
        .merge(llm_subset, on="number", how="inner")
        .merge(expected_results, on="number", how="inner")
    )

    return comparison


def add_correctness_flags(df: pd.DataFrame) -> pd.DataFrame:
    """
    Add boolean columns showing whether rules and LLM outputs match expected labels.

    These flags make downstream comparison much easier.
    """

    comparison = df.copy()

    # Rules correctness by field.
    comparison["rules_category_correct"] = (
        comparison["rules_triage_category"] == comparison["expected_triage_category"]
    )
    comparison["rules_urgency_correct"] = (
        comparison["rules_triage_urgency"] == comparison["expected_urgency"]
    )
    comparison["rules_owner_correct"] = (
        comparison["rules_recommended_owner"] == comparison["expected_owner"]
    )

    # LLM correctness by field.
    comparison["llm_category_correct"] = (
        comparison["llm_triage_category"] == comparison["expected_triage_category"]
    )
    comparison["llm_urgency_correct"] = (
        comparison["llm_triage_urgency"] == comparison["expected_urgency"]
    )
    comparison["llm_owner_correct"] = (
        comparison["llm_recommended_owner"] == comparison["expected_owner"]
    )

    # Agreement flags show whether rules and LLM made the same decision.
    comparison["category_agreement"] = (
        comparison["rules_triage_category"] == comparison["llm_triage_category"]
    )
    comparison["urgency_agreement"] = (
        comparison["rules_triage_urgency"] == comparison["llm_triage_urgency"]
    )
    comparison["owner_agreement"] = (
        comparison["rules_recommended_owner"] == comparison["llm_recommended_owner"]
    )

    return comparison


def add_comparison_outcomes(df: pd.DataFrame) -> pd.DataFrame:
    """
    Add higher-level outcome labels comparing rules and LLM performance.

    This function also creates a recommended hybrid triage strategy:
    - use LLM for category because it performs better semantically
    - use rules for urgency because urgency is policy-driven
    - use LLM for owner because it performs better in the current evaluation

    The hybrid recommendation is based on measured performance, not preference.
    """

    comparison = df.copy()

    # Compare rules and LLM performance for category.
    comparison["category_comparison_outcome"] = comparison.apply(
        lambda row: classify_outcome(
            rules_correct=row["rules_category_correct"],
            llm_correct=row["llm_category_correct"],
        ),
        axis=1,
    )

    # Compare rules and LLM performance for urgency.
    comparison["urgency_comparison_outcome"] = comparison.apply(
        lambda row: classify_outcome(
            rules_correct=row["rules_urgency_correct"],
            llm_correct=row["llm_urgency_correct"],
        ),
        axis=1,
    )

    # Compare rules and LLM performance for owner.
    comparison["owner_comparison_outcome"] = comparison.apply(
        lambda row: classify_outcome(
            rules_correct=row["rules_owner_correct"],
            llm_correct=row["llm_owner_correct"],
        ),
        axis=1,
    )

    # Create a measured hybrid recommendation.
    # Based on the current evaluation:
    # - LLM is strongest for category.
    # - Rules are strongest for urgency.
    # - LLM is strongest for owner.
    comparison["hybrid_triage_category"] = comparison["llm_triage_category"]
    comparison["hybrid_triage_urgency"] = comparison["rules_triage_urgency"]
    comparison["hybrid_recommended_owner"] = comparison["llm_recommended_owner"]

    # Check whether the hybrid result matches the expected labels.
    comparison["hybrid_category_correct"] = (
        comparison["hybrid_triage_category"] == comparison["expected_triage_category"]
    )
    comparison["hybrid_urgency_correct"] = (
        comparison["hybrid_triage_urgency"] == comparison["expected_urgency"]
    )
    comparison["hybrid_owner_correct"] = (
        comparison["hybrid_recommended_owner"] == comparison["expected_owner"]
    )

    # Human review is especially useful when rules and LLM disagree,
    # when the LLM has low confidence, or when the final urgency is Critical.
    comparison["recommended_for_human_review"] = (
        ~comparison["category_agreement"]
        | ~comparison["urgency_agreement"]
        | ~comparison["owner_agreement"]
        | (comparison["llm_confidence"] < 0.70)
        | (comparison["hybrid_triage_urgency"] == "Critical")
    )

    return comparison


def classify_outcome(rules_correct: bool, llm_correct: bool) -> str:
    """
    Classify the comparison outcome for one field.

    This tells us whether rules won, the LLM won, both were right, or both were wrong.
    """

    if rules_correct and llm_correct:
        return "Both Right"

    if rules_correct and not llm_correct:
        return "Rules Better"

    if not rules_correct and llm_correct:
        return "LLM Better"

    return "Both Wrong"


def print_accuracy_summary(df: pd.DataFrame) -> None:
    """
    Print side-by-side accuracy metrics for rules, LLM, and hybrid outputs.

    The hybrid output represents the recommended operating model:
    LLM category, rules urgency, and LLM owner.
    """

    print("\nRules vs. LLM Accuracy Summary")
    print("==============================")
    print(f"Total compared incidents: {len(df)}")

    print("\nRules-Based Classifier")
    print(f"Category accuracy: {calculate_accuracy(df, 'rules_triage_category', 'expected_triage_category'):.0%}")
    print(f"Urgency accuracy:  {calculate_accuracy(df, 'rules_triage_urgency', 'expected_urgency'):.0%}")
    print(f"Owner accuracy:    {calculate_accuracy(df, 'rules_recommended_owner', 'expected_owner'):.0%}")

    print("\nLLM Classifier")
    print(f"Category accuracy: {calculate_accuracy(df, 'llm_triage_category', 'expected_triage_category'):.0%}")
    print(f"Urgency accuracy:  {calculate_accuracy(df, 'llm_triage_urgency', 'expected_urgency'):.0%}")
    print(f"Owner accuracy:    {calculate_accuracy(df, 'llm_recommended_owner', 'expected_owner'):.0%}")

    print("\nHybrid Recommendation")
    print(f"Category accuracy: {calculate_accuracy(df, 'hybrid_triage_category', 'expected_triage_category'):.0%}")
    print(f"Urgency accuracy:  {calculate_accuracy(df, 'hybrid_triage_urgency', 'expected_urgency'):.0%}")
    print(f"Owner accuracy:    {calculate_accuracy(df, 'hybrid_recommended_owner', 'expected_owner'):.0%}")


def print_agreement_summary(df: pd.DataFrame) -> None:
    """
    Print how often rules and LLM agree with each other.

    Agreement is useful because disagreements are strong candidates for human review.
    """

    print("\nRules vs. LLM Agreement")
    print("=======================")
    print(f"Category agreement: {df['category_agreement'].mean():.0%}")
    print(f"Urgency agreement:  {df['urgency_agreement'].mean():.0%}")
    print(f"Owner agreement:    {df['owner_agreement'].mean():.0%}")

    review_count = df["recommended_for_human_review"].sum()
    print(f"Recommended for human review: {review_count} of {len(df)}")


def print_hybrid_recommendation_summary(df: pd.DataFrame) -> None:
    """
    Print the recommended hybrid operating model.

    This translates the evaluation results into an architecture recommendation.
    """

    print("\nRecommended Hybrid Operating Model")
    print("==================================")
    print("Use LLM output for category classification.")
    print("Use rules-based output for urgency classification.")
    print("Use LLM output for owner recommendation.")
    print("Send incidents to human review when rules and LLM disagree, LLM confidence is low, or urgency is Critical.")

    hybrid_review_count = df["recommended_for_human_review"].sum()
    automation_candidate_count = len(df) - hybrid_review_count

    print(f"\nAutomation candidates: {automation_candidate_count} of {len(df)}")
    print(f"Human review candidates: {hybrid_review_count} of {len(df)}")


def print_outcome_summary(df: pd.DataFrame, outcome_column: str) -> None:
    """
    Print counts for comparison outcomes such as Both Right, LLM Better, Rules Better, and Both Wrong.
    """

    print(f"\nOutcome summary for {outcome_column}:")
    print(df[outcome_column].value_counts().to_string())


def print_disagreement_examples(df: pd.DataFrame, limit: int = 10) -> None:
    """
    Print a small sample of incidents where rules and LLM disagree.

    These examples are useful for understanding when human review may be needed.
    """

    disagreements = df[
        ~df["category_agreement"]
        | ~df["urgency_agreement"]
        | ~df["owner_agreement"]
    ]

    if disagreements.empty:
        print("\nNo rules vs. LLM disagreements found.")
        return

    print(f"\nSample disagreement examples, limited to {limit}:")
    for _, row in disagreements.head(limit).iterrows():
        print(
            f"- {row['number']}: "
            f"expected=({row['expected_triage_category']}, {row['expected_urgency']}, {row['expected_owner']}), "
            f"rules=({row['rules_triage_category']}, {row['rules_triage_urgency']}, {row['rules_recommended_owner']}), "
            f"llm=({row['llm_triage_category']}, {row['llm_triage_urgency']}, {row['llm_recommended_owner']}), "
            f"short_description=\"{row['short_description']}\""
        )


def main():
    """
    Compare rules-based triage, LLM-based triage, and expected ground truth.

    This script creates a comparison CSV and prints summary metrics.
    """

    # Load and merge rules, LLM, and expected data.
    comparison = load_comparison_inputs()

    # Add field-level correctness flags.
    comparison = add_correctness_flags(comparison)

    # Add high-level comparison outcomes.
    comparison = add_comparison_outcomes(comparison)

    # Write the detailed comparison dataset.
    comparison.to_csv(COMPARISON_OUTPUT_FILE, index=False)

    # Print summary metrics to the terminal.
    print_accuracy_summary(comparison)
    print_agreement_summary(comparison)
    print_hybrid_recommendation_summary(comparison)

    print_outcome_summary(comparison, "category_comparison_outcome")
    print_outcome_summary(comparison, "urgency_comparison_outcome")
    print_outcome_summary(comparison, "owner_comparison_outcome")

    print_disagreement_examples(comparison)

    print(f"\nWrote comparison output to {COMPARISON_OUTPUT_FILE}")


if __name__ == "__main__":
    main()